/**
 * Principais cidades por estado, usadas no dropdown de busca de prospects.
 * Nao e uma lista exaustiva de municipios — apenas os maiores/mais
 * relevantes de cada estado para prospeccao comercial.
 */
export const BRAZIL_CITIES_BY_STATE: Record<string, string[]> = {
  AC: [
    "Rio Branco",
    "Cruzeiro do Sul",
    "Sena Madureira",
    "Tarauacá",
    "Feijó",
    "Brasiléia",
    "Plácido de Castro",
    "Xapuri",
    "Epitaciolândia",
    "Mâncio Lima",
  ],
  AL: [
    "Maceió",
    "Arapiraca",
    "Palmeira dos Índios",
    "Rio Largo",
    "Penedo",
    "União dos Palmares",
    "Coruripe",
    "São Miguel dos Campos",
    "Delmiro Gouveia",
    "Santana do Ipanema",
    "Marechal Deodoro",
    "Campo Alegre",
  ],
  AP: [
    "Macapá",
    "Santana",
    "Laranjal do Jari",
    "Oiapoque",
    "Mazagão",
    "Porto Grande",
    "Tartarugalzinho",
    "Vitória do Jari",
    "Pedra Branca do Amapari",
    "Calçoene",
  ],
  AM: [
    "Manaus",
    "Parintins",
    "Itacoatiara",
    "Manacapuru",
    "Coari",
    "Tefé",
    "Tabatinga",
    "Maués",
    "Humaitá",
    "Iranduba",
    "Manicoré",
    "Presidente Figueiredo",
  ],
  BA: [
    "Salvador",
    "Feira de Santana",
    "Vitória da Conquista",
    "Camaçari",
    "Juazeiro",
    "Ilhéus",
    "Itabuna",
    "Lauro de Freitas",
    "Jequié",
    "Teixeira de Freitas",
    "Alagoinhas",
    "Barreiras",
    "Porto Seguro",
    "Simões Filho",
    "Paulo Afonso",
  ],
  CE: [
    "Fortaleza",
    "Caucaia",
    "Juazeiro do Norte",
    "Maracanaú",
    "Sobral",
    "Crato",
    "Itapipoca",
    "Maranguape",
    "Iguatu",
    "Quixadá",
    "Pacatuba",
    "Aquiraz",
    "Russas",
    "Horizonte",
    "Tianguá",
    "Barbalha",
    "Canindé",
    "Cascavel",
    "Limoeiro do Norte",
    "Morada Nova",
  ],
  DF: [
    "Brasília",
    "Ceilândia",
    "Taguatinga",
    "Samambaia",
    "Plano Piloto",
    "Águas Claras",
    "Gama",
    "Santa Maria",
    "Recanto das Emas",
    "Guará",
    "Sobradinho",
    "Planaltina",
  ],
  ES: [
    "Vitória",
    "Vila Velha",
    "Cariacica",
    "Serra",
    "Cachoeiro de Itapemirim",
    "Linhares",
    "São Mateus",
    "Colatina",
    "Guarapari",
    "Aracruz",
    "Viana",
    "Nova Venécia",
  ],
  GO: [
    "Goiânia",
    "Aparecida de Goiânia",
    "Anápolis",
    "Rio Verde",
    "Luziânia",
    "Águas Lindas de Goiás",
    "Valparaíso de Goiás",
    "Trindade",
    "Formosa",
    "Novo Gama",
    "Itumbiara",
    "Senador Canedo",
    "Catalão",
    "Jataí",
  ],
  MA: [
    "São Luís",
    "Imperatriz",
    "São José de Ribamar",
    "Timon",
    "Caxias",
    "Codó",
    "Paço do Lumiar",
    "Açailândia",
    "Bacabal",
    "Balsas",
    "Santa Inês",
    "Barra do Corda",
  ],
  MT: [
    "Cuiabá",
    "Várzea Grande",
    "Rondonópolis",
    "Sinop",
    "Tangará da Serra",
    "Cáceres",
    "Sorriso",
    "Lucas do Rio Verde",
    "Primavera do Leste",
    "Barra do Garças",
    "Alta Floresta",
    "Pontes e Lacerda",
  ],
  MS: [
    "Campo Grande",
    "Dourados",
    "Três Lagoas",
    "Corumbá",
    "Ponta Porã",
    "Naviraí",
    "Nova Andradina",
    "Aquidauana",
    "Sidrolândia",
    "Maracaju",
    "Coxim",
    "Paranaíba",
  ],
  MG: [
    "Belo Horizonte",
    "Uberlândia",
    "Contagem",
    "Juiz de Fora",
    "Betim",
    "Montes Claros",
    "Ribeirão das Neves",
    "Uberaba",
    "Governador Valadares",
    "Ipatinga",
    "Sete Lagoas",
    "Divinópolis",
    "Santa Luzia",
    "Ibirité",
    "Poços de Caldas",
    "Patos de Minas",
    "Pouso Alegre",
    "Teófilo Otoni",
  ],
  PA: [
    "Belém",
    "Ananindeua",
    "Santarém",
    "Marabá",
    "Parauapebas",
    "Castanhal",
    "Abaetetuba",
    "Cametá",
    "Bragança",
    "Altamira",
    "Itaituba",
    "Tucuruí",
  ],
  PB: [
    "João Pessoa",
    "Campina Grande",
    "Santa Rita",
    "Patos",
    "Bayeux",
    "Sousa",
    "Cajazeiras",
    "Cabedelo",
    "Guarabira",
    "Sapé",
    "Mamanguape",
    "Esperança",
  ],
  PR: [
    "Curitiba",
    "Londrina",
    "Maringá",
    "Ponta Grossa",
    "Cascavel",
    "São José dos Pinhais",
    "Foz do Iguaçu",
    "Colombo",
    "Guarapuava",
    "Paranaguá",
    "Araucária",
    "Toledo",
    "Apucarana",
    "Pinhais",
    "Campo Largo",
    "Umuarama",
  ],
  PE: [
    "Recife",
    "Jaboatão dos Guararapes",
    "Olinda",
    "Caruaru",
    "Petrolina",
    "Paulista",
    "Cabo de Santo Agostinho",
    "Camaragibe",
    "Garanhuns",
    "Vitória de Santo Antão",
    "Igarassu",
    "Santa Cruz do Capibaribe",
  ],
  PI: [
    "Teresina",
    "Parnaíba",
    "Picos",
    "Piripiri",
    "Floriano",
    "Campo Maior",
    "Barras",
    "União",
    "Altos",
    "José de Freitas",
    "Pedro II",
    "Esperantina",
  ],
  RJ: [
    "Rio de Janeiro",
    "São Gonçalo",
    "Duque de Caxias",
    "Nova Iguaçu",
    "Niterói",
    "Belford Roxo",
    "Campos dos Goytacazes",
    "São João de Meriti",
    "Petrópolis",
    "Volta Redonda",
    "Magé",
    "Macaé",
    "Itaboraí",
    "Cabo Frio",
    "Angra dos Reis",
    "Nova Friburgo",
  ],
  RN: [
    "Natal",
    "Mossoró",
    "Parnamirim",
    "São Gonçalo do Amarante",
    "Macaíba",
    "Ceará-Mirim",
    "Caicó",
    "Açu",
    "Currais Novos",
    "Santa Cruz",
    "Extremoz",
    "Pau dos Ferros",
  ],
  RS: [
    "Porto Alegre",
    "Caxias do Sul",
    "Pelotas",
    "Canoas",
    "Santa Maria",
    "Gravataí",
    "Viamão",
    "Novo Hamburgo",
    "São Leopoldo",
    "Rio Grande",
    "Alvorada",
    "Passo Fundo",
    "Sapucaia do Sul",
    "Uruguaiana",
    "Santa Cruz do Sul",
    "Cachoeirinha",
  ],
  RO: [
    "Porto Velho",
    "Ji-Paraná",
    "Ariquemes",
    "Vilhena",
    "Cacoal",
    "Rolim de Moura",
    "Guajará-Mirim",
    "Jaru",
    "Ouro Preto do Oeste",
    "Pimenta Bueno",
  ],
  RR: [
    "Boa Vista",
    "Rorainópolis",
    "Caracaraí",
    "Alto Alegre",
    "Mucajaí",
    "Cantá",
    "Bonfim",
    "Normandia",
    "Pacaraima",
    "Iracema",
  ],
  SC: [
    "Florianópolis",
    "Joinville",
    "Blumenau",
    "São José",
    "Chapecó",
    "Itajaí",
    "Criciúma",
    "Jaraguá do Sul",
    "Palhoça",
    "Lages",
    "Balneário Camboriú",
    "Brusque",
    "Tubarão",
    "Camboriú",
  ],
  SP: [
    "São Paulo",
    "Guarulhos",
    "Campinas",
    "São Bernardo do Campo",
    "Santo André",
    "Osasco",
    "São José dos Campos",
    "Ribeirão Preto",
    "Sorocaba",
    "Mauá",
    "São José do Rio Preto",
    "Mogi das Cruzes",
    "Santos",
    "Diadema",
    "Jundiaí",
    "Piracicaba",
    "Carapicuíba",
    "Bauru",
    "São Vicente",
    "Franca",
  ],
  SE: [
    "Aracaju",
    "Nossa Senhora do Socorro",
    "Lagarto",
    "Itabaiana",
    "São Cristóvão",
    "Estância",
    "Tobias Barreto",
    "Itabaianinha",
    "Simão Dias",
    "Nossa Senhora da Glória",
  ],
  TO: [
    "Palmas",
    "Araguaína",
    "Gurupi",
    "Porto Nacional",
    "Paraíso do Tocantins",
    "Colinas do Tocantins",
    "Guaraí",
    "Tocantinópolis",
    "Dianópolis",
    "Miracema do Tocantins",
  ],
};
